// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"message-push/app/pusher/service/internal/conf"
	"message-push/app/pusher/service/internal/handler"
	"message-push/app/pusher/service/internal/server"
	"message-push/app/pusher/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	report := service.NewReport(bootstrap, logger)
	sendService := service.NewSendService(report, logger)
	webSocketHandler := handler.NewWebSocketHandler(logger, sendService)
	httpServer := server.NewHTTPServer(bootstrap, webSocketHandler)
	kafkaServer := server.NewKafkaServer(bootstrap, sendService)
	grpcServer := server.NewGRPCServer(bootstrap, sendService)
	app := newApp(logger, httpServer, kafkaServer, grpcServer)
	return app, func() {
	}, nil
}
