// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"message-push/app/pusher/service/internal/conf"
	"message-push/app/pusher/service/internal/server"
	"message-push/app/pusher/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	demo := service.NewDemo(logger)
	grpcServer := server.NewGRPCServer(bootstrap, demo, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
