version: '3'

services:
  # 业务服务
  manager:
    image: manager-service:latest
    environment:
      - THIRD_COMPONENT=43.138.114.41
    container_name: manager
    ports:
      - "8800:8800"
    networks:
      - app-network

  receiver:
    image: receiver-service:latest
    environment:
      - THIRD_COMPONENT=43.138.114.41
    container_name: receiver
    ports:
      - "8000:8000"
    networks:
      - app-network

  pusher_0:
    image: pusher-service:latest
    environment:
      - NODE_NAME=pusher_0
      - TOPIC=one_topic
      - PORT=7999
      - THIRD_COMPONENT=43.138.114.41
    container_name: pusher0
    ports:
      - "7999:7999"
    networks:
      - app-network

  pusher_1:
    image: pusher-service:latest
    environment:
      - NODE_NAME=pusher_1
      - TOPIC=one_topic
      - PORT=7998
      - THIRD_COMPONENT=43.138.114.41
    container_name: pusher1
    ports:
      - "7998:7998"
    networks:
      - app-network

  pusher_2:
    image: pusher-service:latest
    environment:
      - NODE_NAME=pusher_2
      - TOPIC=two_topic
      - PORT=7997
      - THIRD_COMPONENT=43.138.114.41
    container_name: pusher2
    ports:
      - "7997:7997"
    networks:
      - app-network

# 共享网络和数据卷
networks:
  app-network:
    driver: bridge