version: '3'

services:
  # 业务服务
  manager:
    image: manager-service:latest
    container_name: manager
    ports:
      - "8008:8008"
      - "8800:8800"
    networks:
      - app-network

  receiver:
    image: receiver-service:latest
    container_name: receiver
    ports:
      - "8000:8000"
    networks:
      - app-network

  pusher0:
    image: pusher-service:latest
    environment:
      - NODE_PATH=/push_services/pushers/pusher_0
      - TOPIC=one_topic
      - PORT=7999
      - GRPC_PORT=7099
    container_name: pusher0
    ports:
      - "7999:7999"
      - "7099:7099"
    networks:
      - app-network

  pusher1:
    image: pusher-service:latest
    environment:
      - NODE_PATH=/push_services/pushers/pusher_1
      - TOPIC=two_topic
      - PORT=7998
      - GRPC_PORT=7098
    container_name: pusher1
    ports:
      - "7998:7998"
      - "7098:7098"
    networks:
      - app-network

  pusher2:
    image: pusher-service:latest
    environment:
      - NODE_PATH=/push_services/pushers/pusher_2
      - TOPIC=two_topic
      - PORT=7997
      - GRPC_PORT=7097
    container_name: pusher2
    ports:
      - "7997:7997"
      - "7097:7097"
    networks:
      - app-network

# 共享网络和数据卷
networks:
  app-network:
    driver: bridge