server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8001
    timeout: 1s
data:
  database:
    driver: mysql
    source: app_user:000@tcp(mysql:3306)/messagepush?parseTime=True&loc=Local
  redis:
    addr: redis:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    brokers:
      - kafka:9092
    topic: demo
