server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:000@tcp(${THIRD_COMPONENT:localhost}:3306)/messagepush?parseTime=True&loc=Local
  redis:
    addr: ${THIRD_COMPONENT:localhost}:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  grpc:
    endpoint: manager:8800
    timeout: 1000
