server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:8001
    timeout: 5s
data:
  database:
    driver: mysql
    source: root:000@tcp(43.138.114.41:3306)/messagepush?parseTime=True&loc=Local
  redis:
    addr: 43.138.114.41:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  grpc:
    endpoint: 127.0.0.1:9000
    timeout: 5000
