// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"message-push/app/access/service/internal/conf"
	"message-push/app/access/service/internal/data"
	"message-push/app/access/service/internal/server"
	"message-push/app/access/service/internal/service"
	"message-push/app/access/service/internal/usecase"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	demo := data.NewDemo(dataData, logger)
	demoUsecase := usecase.NewDemo(logger, demo)
	serviceDemo := service.NewDemo(logger, demoUsecase)
	httpServer := server.NewHTTPServer(confServer, serviceDemo)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
