server:
  http:
    addr: 0.0.0.0:${PORT}
    timeout: 5s
data:
  database:
    driver: mysql
    source: root:000@tcp(43.138.114.41:3306)/messagepush?parseTime=True&loc=Local
  redis:
    addr: 43.138.114.41:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    brokers:
      - 43.138.114.41:9092
    topic: ${TOPIC}
    group: two_group
  zookeeper:
    addr: 43.138.114.41:2181
    senders_root: "/push_services/senders"
    senders_name: "/push_services/pushers"
    timeout: 5s
report:
  host: 127.0.0.1
  port: ${PORT}
  topic: ${TOPIC}
  weight: 5
  nodePath: /push_services/pushers/${NODE_NAME}
