server:
  http:
    addr: 0.0.0.0:0000
    timeout: 5s
data:
  database:
    driver: mysql
    source: "root:000@tcp(8.152.156.127:3306)/messagepush?parseTime=True&loc=Local"
  redis:
    addr: 8.152.156.127:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    brokers:
      - 8.152.156.127:9092
    topic: TOPIC
    group: two_group
  zookeeper:
    addr: 8.152.156.127:2181
    senders_root: "/push_services/senders"
    senders_name: "/push_services/pushers"
    timeout: 5s
report:
  host: 39.107.58.199
  port: 0000
  topic: TOPIC
  weight: 5
  nodePath: NODE_PATH
