server:
  http:
    addr: 0.0.0.0:${PORT:8000}
    timeout: 5s
data:
  database:
    driver: mysql
    source: "root:000@tcp(${THIRD_COMPONENT:localhost}:3306)/messagepush?parseTime=True&loc=Local"
  redis:
    addr: "${THIRD_COMPONENT:localhost}:6379"
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    brokers:
      - "${THIRD_COMPONENT:localhost}:9092"
    topic: "${TOPIC:one_topic}"
    group: two_group
  zookeeper:
    addr: "${THIRD_COMPONENT:localhost}:2181"
    senders_root: "/push_services/senders"
    senders_name: "/push_services/pushers"
    timeout: 5s
report:
  host: 127.0.0.1
  port: "${PORT:8000}"
  topic: "${TOPIC:one_topic}"
  weight: 5
  nodePath: "/push_services/pushers/${NODE_NAME:pusher_0}"
