server:
  http:
    addr: 0.0.0.0:0000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:0000
    timeout: 5s
data:
  database:
    driver: mysql
    source: "root:000@tcp(60.205.244.34:3306)/messagepush?parseTime=True&loc=Local"
  redis:
    addr: 60.205.244.34:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    brokers:
      - 60.205.244.34:9092
    topic: TOPIC
    group: GROUP
  zookeeper:
    addr: 60.205.244.34:2181
    senders_root: "/push_services/senders"
    senders_name: "/push_services/pushers"
    timeout: 5s
report:
  host: 8.147.117.133
  port: 0000
  topic: TOPIC
  weight: 5
  nodePath: NODE_PATH
