// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: server/v1/directSend.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DirectSendService_DirectSend_FullMethodName = "/server.v1.DirectSendService/DirectSend"
)

// DirectSendServiceClient is the client API for DirectSendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DirectSendServiceClient interface {
	DirectSend(ctx context.Context, in *DirectSendRequest, opts ...grpc.CallOption) (*DirectSendResponse, error)
}

type directSendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectSendServiceClient(cc grpc.ClientConnInterface) DirectSendServiceClient {
	return &directSendServiceClient{cc}
}

func (c *directSendServiceClient) DirectSend(ctx context.Context, in *DirectSendRequest, opts ...grpc.CallOption) (*DirectSendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectSendResponse)
	err := c.cc.Invoke(ctx, DirectSendService_DirectSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectSendServiceServer is the server API for DirectSendService service.
// All implementations must embed UnimplementedDirectSendServiceServer
// for forward compatibility.
type DirectSendServiceServer interface {
	DirectSend(context.Context, *DirectSendRequest) (*DirectSendResponse, error)
	mustEmbedUnimplementedDirectSendServiceServer()
}

// UnimplementedDirectSendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDirectSendServiceServer struct{}

func (UnimplementedDirectSendServiceServer) DirectSend(context.Context, *DirectSendRequest) (*DirectSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DirectSend not implemented")
}
func (UnimplementedDirectSendServiceServer) mustEmbedUnimplementedDirectSendServiceServer() {}
func (UnimplementedDirectSendServiceServer) testEmbeddedByValue()                           {}

// UnsafeDirectSendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirectSendServiceServer will
// result in compilation errors.
type UnsafeDirectSendServiceServer interface {
	mustEmbedUnimplementedDirectSendServiceServer()
}

func RegisterDirectSendServiceServer(s grpc.ServiceRegistrar, srv DirectSendServiceServer) {
	// If the following call pancis, it indicates UnimplementedDirectSendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DirectSendService_ServiceDesc, srv)
}

func _DirectSendService_DirectSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectSendServiceServer).DirectSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DirectSendService_DirectSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectSendServiceServer).DirectSend(ctx, req.(*DirectSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DirectSendService_ServiceDesc is the grpc.ServiceDesc for DirectSendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DirectSendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.v1.DirectSendService",
	HandlerType: (*DirectSendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DirectSend",
			Handler:    _DirectSendService_DirectSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/v1/directSend.proto",
}
