// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: server/v1/searchPusher.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId    string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *PushSearchRequest) Reset() {
	*x = PushSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_v1_searchPusher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSearchRequest) ProtoMessage() {}

func (x *PushSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_searchPusher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSearchRequest.ProtoReflect.Descriptor instead.
func (*PushSearchRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_searchPusher_proto_rawDescGZIP(), []int{0}
}

func (x *PushSearchRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PushSearchRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type PushSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *PushSearchResponse) Reset() {
	*x = PushSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_v1_searchPusher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSearchResponse) ProtoMessage() {}

func (x *PushSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_searchPusher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSearchResponse.ProtoReflect.Descriptor instead.
func (*PushSearchResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_searchPusher_proto_rawDescGZIP(), []int{1}
}

func (x *PushSearchResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_server_v1_searchPusher_proto protoreflect.FileDescriptor

var file_server_v1_searchPusher_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x11, 0x50, 0x75, 0x73, 0x68, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x26, 0x0a, 0x12, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0x6d, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x12, 0x5d, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x3a, 0x01, 0x2a, 0x22, 0x07,
	0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x19, 0x5a, 0x17, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_v1_searchPusher_proto_rawDescOnce sync.Once
	file_server_v1_searchPusher_proto_rawDescData = file_server_v1_searchPusher_proto_rawDesc
)

func file_server_v1_searchPusher_proto_rawDescGZIP() []byte {
	file_server_v1_searchPusher_proto_rawDescOnce.Do(func() {
		file_server_v1_searchPusher_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_v1_searchPusher_proto_rawDescData)
	})
	return file_server_v1_searchPusher_proto_rawDescData
}

var file_server_v1_searchPusher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_v1_searchPusher_proto_goTypes = []interface{}{
	(*PushSearchRequest)(nil),  // 0: server.v1.PushSearchRequest
	(*PushSearchResponse)(nil), // 1: server.v1.PushSearchResponse
}
var file_server_v1_searchPusher_proto_depIdxs = []int32{
	0, // 0: server.v1.SearchPusher.PushSearch:input_type -> server.v1.PushSearchRequest
	1, // 1: server.v1.SearchPusher.PushSearch:output_type -> server.v1.PushSearchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_v1_searchPusher_proto_init() }
func file_server_v1_searchPusher_proto_init() {
	if File_server_v1_searchPusher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_v1_searchPusher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_v1_searchPusher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_v1_searchPusher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_searchPusher_proto_goTypes,
		DependencyIndexes: file_server_v1_searchPusher_proto_depIdxs,
		MessageInfos:      file_server_v1_searchPusher_proto_msgTypes,
	}.Build()
	File_server_v1_searchPusher_proto = out.File
	file_server_v1_searchPusher_proto_rawDesc = nil
	file_server_v1_searchPusher_proto_goTypes = nil
	file_server_v1_searchPusher_proto_depIdxs = nil
}
