// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.3
// - protoc             v3.12.4
// source: server/v1/searchPusher.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSearchPusherPushSearch = "/server.v1.SearchPusher/PushSearch"

type SearchPusherHTTPServer interface {
	PushSearch(context.Context, *PushSearchRequest) (*PushSearchResponse, error)
}

func RegisterSearchPusherHTTPServer(s *http.Server, srv SearchPusherHTTPServer) {
	r := s.Route("/")
	r.POST("/search", _SearchPusher_PushSearch0_HTTP_Handler(srv))
}

func _SearchPusher_PushSearch0_HTTP_Handler(srv SearchPusherHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PushSearchRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSearchPusherPushSearch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PushSearch(ctx, req.(*PushSearchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PushSearchResponse)
		return ctx.Result(200, reply)
	}
}

type SearchPusherHTTPClient interface {
	PushSearch(ctx context.Context, req *PushSearchRequest, opts ...http.CallOption) (rsp *PushSearchResponse, err error)
}

type SearchPusherHTTPClientImpl struct {
	cc *http.Client
}

func NewSearchPusherHTTPClient(client *http.Client) SearchPusherHTTPClient {
	return &SearchPusherHTTPClientImpl{client}
}

func (c *SearchPusherHTTPClientImpl) PushSearch(ctx context.Context, in *PushSearchRequest, opts ...http.CallOption) (*PushSearchResponse, error) {
	var out PushSearchResponse
	pattern := "/search"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSearchPusherPushSearch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
