// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"message-push/app/manager/service/internal/conf"
	"message-push/app/manager/service/internal/data"
	"message-push/app/manager/service/internal/server"
	"message-push/app/manager/service/internal/service"
	"message-push/app/manager/service/internal/usecase"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	loadBalancer := data.NewLoadBalancer(bootstrap)
	triggerRepo := data.NewTriggerRepo(logger, dataData, loadBalancer)
	triggerUsecase := usecase.NewTriggerUsecase(logger, triggerRepo)
	triggerService := service.NewTriggerService(logger, triggerUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, triggerService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
