// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"message-push/app/receiver/common/model/po/ent/businessclient"
	"message-push/app/receiver/common/model/po/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BusinessClientDelete is the builder for deleting a BusinessClient entity.
type BusinessClientDelete struct {
	config
	hooks    []Hook
	mutation *BusinessClientMutation
}

// Where appends a list predicates to the BusinessClientDelete builder.
func (bcd *BusinessClientDelete) Where(ps ...predicate.BusinessClient) *BusinessClientDelete {
	bcd.mutation.Where(ps...)
	return bcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bcd *BusinessClientDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bcd.sqlExec, bcd.mutation, bcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bcd *BusinessClientDelete) ExecX(ctx context.Context) int {
	n, err := bcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bcd *BusinessClientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(businessclient.Table, sqlgraph.NewFieldSpec(businessclient.FieldID, field.TypeInt))
	if ps := bcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bcd.mutation.done = true
	return affected, err
}

// BusinessClientDeleteOne is the builder for deleting a single BusinessClient entity.
type BusinessClientDeleteOne struct {
	bcd *BusinessClientDelete
}

// Where appends a list predicates to the BusinessClientDelete builder.
func (bcdo *BusinessClientDeleteOne) Where(ps ...predicate.BusinessClient) *BusinessClientDeleteOne {
	bcdo.bcd.mutation.Where(ps...)
	return bcdo
}

// Exec executes the deletion query.
func (bcdo *BusinessClientDeleteOne) Exec(ctx context.Context) error {
	n, err := bcdo.bcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{businessclient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bcdo *BusinessClientDeleteOne) ExecX(ctx context.Context) {
	if err := bcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
