// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"message-push/app/receiver/common/model/po/ent/businessapp"
	"message-push/app/receiver/common/model/po/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BusinessAppDelete is the builder for deleting a BusinessApp entity.
type BusinessAppDelete struct {
	config
	hooks    []Hook
	mutation *BusinessAppMutation
}

// Where appends a list predicates to the BusinessAppDelete builder.
func (bad *BusinessAppDelete) Where(ps ...predicate.BusinessApp) *BusinessAppDelete {
	bad.mutation.Where(ps...)
	return bad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bad *BusinessAppDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bad.sqlExec, bad.mutation, bad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bad *BusinessAppDelete) ExecX(ctx context.Context) int {
	n, err := bad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bad *BusinessAppDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(businessapp.Table, sqlgraph.NewFieldSpec(businessapp.FieldID, field.TypeInt))
	if ps := bad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bad.mutation.done = true
	return affected, err
}

// BusinessAppDeleteOne is the builder for deleting a single BusinessApp entity.
type BusinessAppDeleteOne struct {
	bad *BusinessAppDelete
}

// Where appends a list predicates to the BusinessAppDelete builder.
func (bado *BusinessAppDeleteOne) Where(ps ...predicate.BusinessApp) *BusinessAppDeleteOne {
	bado.bad.mutation.Where(ps...)
	return bado
}

// Exec executes the deletion query.
func (bado *BusinessAppDeleteOne) Exec(ctx context.Context) error {
	n, err := bado.bad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{businessapp.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bado *BusinessAppDeleteOne) ExecX(ctx context.Context) {
	if err := bado.Exec(ctx); err != nil {
		panic(err)
	}
}
