// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"message-push/app/receiver/common/model/po/ent/businessclient"
	"message-push/app/receiver/common/model/po/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BusinessClientQuery is the builder for querying BusinessClient entities.
type BusinessClientQuery struct {
	config
	ctx        *QueryContext
	order      []businessclient.OrderOption
	inters     []Interceptor
	predicates []predicate.BusinessClient
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BusinessClientQuery builder.
func (bcq *BusinessClientQuery) Where(ps ...predicate.BusinessClient) *BusinessClientQuery {
	bcq.predicates = append(bcq.predicates, ps...)
	return bcq
}

// Limit the number of records to be returned by this query.
func (bcq *BusinessClientQuery) Limit(limit int) *BusinessClientQuery {
	bcq.ctx.Limit = &limit
	return bcq
}

// Offset to start from.
func (bcq *BusinessClientQuery) Offset(offset int) *BusinessClientQuery {
	bcq.ctx.Offset = &offset
	return bcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bcq *BusinessClientQuery) Unique(unique bool) *BusinessClientQuery {
	bcq.ctx.Unique = &unique
	return bcq
}

// Order specifies how the records should be ordered.
func (bcq *BusinessClientQuery) Order(o ...businessclient.OrderOption) *BusinessClientQuery {
	bcq.order = append(bcq.order, o...)
	return bcq
}

// First returns the first BusinessClient entity from the query.
// Returns a *NotFoundError when no BusinessClient was found.
func (bcq *BusinessClientQuery) First(ctx context.Context) (*BusinessClient, error) {
	nodes, err := bcq.Limit(1).All(setContextOp(ctx, bcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{businessclient.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bcq *BusinessClientQuery) FirstX(ctx context.Context) *BusinessClient {
	node, err := bcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BusinessClient ID from the query.
// Returns a *NotFoundError when no BusinessClient ID was found.
func (bcq *BusinessClientQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bcq.Limit(1).IDs(setContextOp(ctx, bcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{businessclient.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bcq *BusinessClientQuery) FirstIDX(ctx context.Context) int {
	id, err := bcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BusinessClient entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BusinessClient entity is found.
// Returns a *NotFoundError when no BusinessClient entities are found.
func (bcq *BusinessClientQuery) Only(ctx context.Context) (*BusinessClient, error) {
	nodes, err := bcq.Limit(2).All(setContextOp(ctx, bcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{businessclient.Label}
	default:
		return nil, &NotSingularError{businessclient.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bcq *BusinessClientQuery) OnlyX(ctx context.Context) *BusinessClient {
	node, err := bcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BusinessClient ID in the query.
// Returns a *NotSingularError when more than one BusinessClient ID is found.
// Returns a *NotFoundError when no entities are found.
func (bcq *BusinessClientQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bcq.Limit(2).IDs(setContextOp(ctx, bcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{businessclient.Label}
	default:
		err = &NotSingularError{businessclient.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bcq *BusinessClientQuery) OnlyIDX(ctx context.Context) int {
	id, err := bcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BusinessClients.
func (bcq *BusinessClientQuery) All(ctx context.Context) ([]*BusinessClient, error) {
	ctx = setContextOp(ctx, bcq.ctx, ent.OpQueryAll)
	if err := bcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BusinessClient, *BusinessClientQuery]()
	return withInterceptors[[]*BusinessClient](ctx, bcq, qr, bcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bcq *BusinessClientQuery) AllX(ctx context.Context) []*BusinessClient {
	nodes, err := bcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BusinessClient IDs.
func (bcq *BusinessClientQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bcq.ctx.Unique == nil && bcq.path != nil {
		bcq.Unique(true)
	}
	ctx = setContextOp(ctx, bcq.ctx, ent.OpQueryIDs)
	if err = bcq.Select(businessclient.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bcq *BusinessClientQuery) IDsX(ctx context.Context) []int {
	ids, err := bcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bcq *BusinessClientQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bcq.ctx, ent.OpQueryCount)
	if err := bcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bcq, querierCount[*BusinessClientQuery](), bcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bcq *BusinessClientQuery) CountX(ctx context.Context) int {
	count, err := bcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bcq *BusinessClientQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bcq.ctx, ent.OpQueryExist)
	switch _, err := bcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bcq *BusinessClientQuery) ExistX(ctx context.Context) bool {
	exist, err := bcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BusinessClientQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bcq *BusinessClientQuery) Clone() *BusinessClientQuery {
	if bcq == nil {
		return nil
	}
	return &BusinessClientQuery{
		config:     bcq.config,
		ctx:        bcq.ctx.Clone(),
		order:      append([]businessclient.OrderOption{}, bcq.order...),
		inters:     append([]Interceptor{}, bcq.inters...),
		predicates: append([]predicate.BusinessClient{}, bcq.predicates...),
		// clone intermediate query.
		sql:       bcq.sql.Clone(),
		path:      bcq.path,
		modifiers: append([]func(*sql.Selector){}, bcq.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BusinessClient.Query().
//		GroupBy(businessclient.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bcq *BusinessClientQuery) GroupBy(field string, fields ...string) *BusinessClientGroupBy {
	bcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BusinessClientGroupBy{build: bcq}
	grbuild.flds = &bcq.ctx.Fields
	grbuild.label = businessclient.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.BusinessClient.Query().
//		Select(businessclient.FieldName).
//		Scan(ctx, &v)
func (bcq *BusinessClientQuery) Select(fields ...string) *BusinessClientSelect {
	bcq.ctx.Fields = append(bcq.ctx.Fields, fields...)
	sbuild := &BusinessClientSelect{BusinessClientQuery: bcq}
	sbuild.label = businessclient.Label
	sbuild.flds, sbuild.scan = &bcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BusinessClientSelect configured with the given aggregations.
func (bcq *BusinessClientQuery) Aggregate(fns ...AggregateFunc) *BusinessClientSelect {
	return bcq.Select().Aggregate(fns...)
}

func (bcq *BusinessClientQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bcq); err != nil {
				return err
			}
		}
	}
	for _, f := range bcq.ctx.Fields {
		if !businessclient.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bcq.path != nil {
		prev, err := bcq.path(ctx)
		if err != nil {
			return err
		}
		bcq.sql = prev
	}
	return nil
}

func (bcq *BusinessClientQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BusinessClient, error) {
	var (
		nodes = []*BusinessClient{}
		_spec = bcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BusinessClient).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BusinessClient{config: bcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(bcq.modifiers) > 0 {
		_spec.Modifiers = bcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (bcq *BusinessClientQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bcq.querySpec()
	if len(bcq.modifiers) > 0 {
		_spec.Modifiers = bcq.modifiers
	}
	_spec.Node.Columns = bcq.ctx.Fields
	if len(bcq.ctx.Fields) > 0 {
		_spec.Unique = bcq.ctx.Unique != nil && *bcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bcq.driver, _spec)
}

func (bcq *BusinessClientQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(businessclient.Table, businessclient.Columns, sqlgraph.NewFieldSpec(businessclient.FieldID, field.TypeInt))
	_spec.From = bcq.sql
	if unique := bcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bcq.path != nil {
		_spec.Unique = true
	}
	if fields := bcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, businessclient.FieldID)
		for i := range fields {
			if fields[i] != businessclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bcq *BusinessClientQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bcq.driver.Dialect())
	t1 := builder.Table(businessclient.Table)
	columns := bcq.ctx.Fields
	if len(columns) == 0 {
		columns = businessclient.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bcq.sql != nil {
		selector = bcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bcq.ctx.Unique != nil && *bcq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range bcq.modifiers {
		m(selector)
	}
	for _, p := range bcq.predicates {
		p(selector)
	}
	for _, p := range bcq.order {
		p(selector)
	}
	if offset := bcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (bcq *BusinessClientQuery) ForUpdate(opts ...sql.LockOption) *BusinessClientQuery {
	if bcq.driver.Dialect() == dialect.Postgres {
		bcq.Unique(false)
	}
	bcq.modifiers = append(bcq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return bcq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (bcq *BusinessClientQuery) ForShare(opts ...sql.LockOption) *BusinessClientQuery {
	if bcq.driver.Dialect() == dialect.Postgres {
		bcq.Unique(false)
	}
	bcq.modifiers = append(bcq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return bcq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (bcq *BusinessClientQuery) Modify(modifiers ...func(s *sql.Selector)) *BusinessClientSelect {
	bcq.modifiers = append(bcq.modifiers, modifiers...)
	return bcq.Select()
}

// BusinessClientGroupBy is the group-by builder for BusinessClient entities.
type BusinessClientGroupBy struct {
	selector
	build *BusinessClientQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bcgb *BusinessClientGroupBy) Aggregate(fns ...AggregateFunc) *BusinessClientGroupBy {
	bcgb.fns = append(bcgb.fns, fns...)
	return bcgb
}

// Scan applies the selector query and scans the result into the given value.
func (bcgb *BusinessClientGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bcgb.build.ctx, ent.OpQueryGroupBy)
	if err := bcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BusinessClientQuery, *BusinessClientGroupBy](ctx, bcgb.build, bcgb, bcgb.build.inters, v)
}

func (bcgb *BusinessClientGroupBy) sqlScan(ctx context.Context, root *BusinessClientQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bcgb.fns))
	for _, fn := range bcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bcgb.flds)+len(bcgb.fns))
		for _, f := range *bcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BusinessClientSelect is the builder for selecting fields of BusinessClient entities.
type BusinessClientSelect struct {
	*BusinessClientQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bcs *BusinessClientSelect) Aggregate(fns ...AggregateFunc) *BusinessClientSelect {
	bcs.fns = append(bcs.fns, fns...)
	return bcs
}

// Scan applies the selector query and scans the result into the given value.
func (bcs *BusinessClientSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bcs.ctx, ent.OpQuerySelect)
	if err := bcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BusinessClientQuery, *BusinessClientSelect](ctx, bcs.BusinessClientQuery, bcs, bcs.inters, v)
}

func (bcs *BusinessClientSelect) sqlScan(ctx context.Context, root *BusinessClientQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bcs.fns))
	for _, fn := range bcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (bcs *BusinessClientSelect) Modify(modifiers ...func(s *sql.Selector)) *BusinessClientSelect {
	bcs.modifiers = append(bcs.modifiers, modifiers...)
	return bcs
}
