// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DemosColumns holds the columns for the "demos" table.
	DemosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Nullable: true, Size: 10},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
	}
	// DemosTable holds the schema information for the "demos" table.
	DemosTable = &schema.Table{
		Name:       "demos",
		Columns:    DemosColumns,
		PrimaryKey: []*schema.Column{DemosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DemosTable,
	}
)

func init() {
}
