server:
  http:
    addr: 0.0.0.0:8008
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8800
    timeout: 1s
data:
  database:
    driver: mysql
    source: "root:000@tcp(60.205.244.34:3306)/messagepush?parseTime=True&loc=Local"
  kafka:
    brokers:
      - 60.205.244.34:9092
    topic:
      - one_topic
      - two_topic
  zookeeper:
    addr: 60.205.244.34:2181
    senders_root: "/push_services/pushers"
    senders_name: "/push_services/pushers"
    timeout: 5s
  grpc:
    endpoint: pusher0:7099
    timeout: 1000
