server:
  http:
    addr: 0.0.0.0:8008
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8800
    timeout: 1s
data:
  database:
    driver: mysql
    source: "root:000@tcp(8.152.156.127:3306)/messagepush?parseTime=True&loc=Local"
  kafka:
    brokers:
      - 8.152.156.127:9092
    topic:
      - one_topic
      - two_topic
  zookeeper:
    addr: 8.152.156.127:2181
    senders_root: "/push_services/pushers"
    senders_name: "/push_services/pushers"
    timeout: 5s
